### PR TITLE
Make Dryspell drier

### PR DESCRIPTION
**Pull request by hexdefined**
While Dryspell is active, prevent stains and make fire impossible to extinguish

### CODE REVIEW

**Comment by Miczu** [comment]
@hexdefined I'm getting errors each frame if I'm stained at the moment of DrySpell activating
image

**Comment by Miczu** [comment]
I get similar error if after voting dryspell, I get the "shrooms" status effect
image
image
Game is a bit laggy when throwing errors.

**Comment by Miczu** [comment]
If it helps, I used noita_dev.exe to have the console

**Comment by hexdefined** [comment]
I can't reproduce either of those, with logs from `noita_dev.exe` and Component Explorer. The error implies a `GameEffectComponent` is missing `caused_by_stains`, which... should always be there?

I could try working around the error or optimising more, but I don't know what could be causing that.

**Comment by Miczu** [comment]
I'll check if my jank noita is up to date or older version...

**Comment by hexdefined** [comment]
I optimised it a bit, since the stain checking/removing only really needs to happen once. Only the fire tracking code needs to run repeatedly.

That should make that error only happen once at the start. Stain removal probably wouldn't work, but at least it won't spam errors.

**Comment by hexdefined** [comment]
I just noticed a bug that I'll need to fix...

**Comment by hexdefined** [comment]
I was removing status effects by game effect name before. That worked fine for things like `WET`, but (for example) removing `REGENERATION` did nothing because the status effect name is `HP_REGENERATION`. And because `SpriteStainsComponent` was disabled... the stain would never wear off.

Fixed.

**Comment by Miczu** [comment]
If player is wet, berserk, invisible stained at the time of dryspell vote taking effect, the stains become permanent 😢 (until dry spell ends)

**Comment by Miczu** [comment]
On the bright side, I didn't see any errors in console 👍

**Comment by hexdefined** [comment]
>the stains become permanent

That's not surprising, given the previous error you saw. When it can't detect that a status effect is caused by a stain, it won't remove it.

(Which was what I mentioned earlier:)

>Stain removal probably wouldn't work, but at least it won't spam errors.

It still removes all stains when I test it.

I can try looking for an alternative method, but it might end up being something ugly like manually iterating over all stain status effect names and attempting to blindly remove them from the player.

**Comment by hexdefined** [comment]
I added a Repelling Cape (`STAINS_DROP_FASTER`) effect as a fallback. If removing stains fails, it now doesn't disable stains, and relies on `STAINS_DROP_FASTER` instead. That means that moving at all after getting stained instantly removes the stain (it's impossible to stay submerged because liquids are removed).

That should avoid stains ever becoming permanent.

**Comment by hexdefined** [comment]
Simplified the stain removal code, and tested on an old Noita build as well as the current one. The fallback for old versions works well enough.

**Comment by Miczu** [comment]
Got around testing it on updated noita, looks good.

**Review by Miczu — APPROVED** [review]

**Pull request merged**
