### PR TITLE
Spicy Blood TI Vote

### PR DESCRIPTION
**Pull request by Conga0**
New vote option: Spicy Blood
Enemies are given a random dangerous blood type (90% for acid, 9% chance for lava, 1% chance for polymorphine) and severely increased blood multipliers to go with it.
Additionally, enemies can't take damage from their given blood type (However, polymorphine will still polymorph to compensate for the fact enemies are bleeding polymorphine everywhere)

Extended the duration of Teleport Nullification to 60 seconds (up from 40 seconds)
Increased the chance for special delusions to compensate for statistical vote rarity

### CODE REVIEW

**Comment by Miczu** [comment]
Can you extend the timer of rare blood instead of adding new effect entity? Those don't appear to interact well and clutter effect icons when multiple one are in effect.

Maybe boost the odds of each outcome too. 60% acid, 30% lava, 10% poly... can't even test poly in game it's so rare.

Any reason for picking sheep poly instead random poly? 
I feel like magic_liquid_random_polymorph would be less deadly when mina gets poly, but "content" when enemies get randomly changed would be better.

**Comment by Conga0** [comment]
> Can you extend the timer of rare blood instead of adding new effect entity? Those don't appear to interact well and clutter effect icons when multiple one are in effect.
> 
> Maybe boost the odds of each outcome too. 60% acid, 30% lava, 10% poly... can't even test poly in game it's so rare.
> 
> Any reason for picking sheep poly instead random poly? I feel like magic_liquid_random_polymorph would be less deadly when mina gets poly, but "content" when enemies get randomly changed would be better.

Extending the buff timer and updating the icon should be easy

Polymorph is intentionally rare as a surprise outcome, sort of how you can vote derandomized enemies plenty of times but only extremely rarely do you end up rolling something laughably bad like Bridge Boss, I've tested it in-game and it works though if that's enough

Making polymorphine into the chaotic variant does sound better though, I'll tweak it with the push for the icon update

**Comment by Miczu** [comment]
My worry with 1% votes is that combined with first appearance curse it will be an impossible long wait until it shows up. 
0.99 ^ 69 ~= 0.4998
So after 69 votes you have a coin flip for it to show up (can't make that math up).
So depending on the luck, whole year could pass before it shows up.

**Comment by Conga0** [comment]
I'm not sure what you mean by first appearance curse, but I can't imagine it would be longer than a month for polymorphine blood to show up.

Lowballing it and assuming Chase only does 10 TI runs in a week total, combined with how many opportunities you get to vote on each run, it should easily appear at least once per month if it's a semi-popular option.

I see it in the same pool as Delusional which also has a super rare occurrence which can happen, if the vote itself is more frequently voted for then it makes sense to keep the chance of the rare thing happening very low, whereas if it ends up being an unpopular vote then it'd make sense to increase the 1% to a higher value to compensate.

I like having these very rare vote outcomes in TI to give chat something to be WOW'd at every month, to make TI feel like it's staying fresh even without having new updates added to it.

I think since it's an a deadly vote + gamba, both of which chat loves, it'll be popular enough to justify polymorphine blood being such a rare chance, but if it ends up being less popular, it would be easy to adjust the numbers later to compensate.

I also believe it makes more sense to keep the 'jackpot' hidden rather than increasing the chance artifically, since if polymorphine blood appears early into the vote's life, I've noticed that's when chase pays the most attention to what TI votes actually do.
If it rolls polymorphine early into it's addition, Chase will have the expectation in the back of his mind that it could be polymorphine that appears and won't be nearly as surprised when it happens later (repeatedly).

**Comment by Conga0** [comment]
I've updated the chance for polymorph to be 2% instead of 1% in the most recent push

**Comment by Miczu** [comment]
Timer extension looks good, but I was surprised that it swaps blood type on extension, but that's fine.

Is it intended for blood type to stick on affected enemies past the effect timer? Not sure if player expectation would be "back to normal" after the timer ends, but it wouldn't be the first vote option to have this issue.

It would be funny if HM fish got new blood, but that's just me.

I'm fine with merging this as is if you don't want to add any more changes.

**Comment by Conga0** [comment]
It's meant to extend past the vote timer in the same way derandomised projectiles and some other votes do, there isn't any thing else major I want to add so I'm fine with seeing it merged as is

**Review by Miczu — APPROVED** [review]
Looks good

**Pull request merged**
