### PR TITLE
New outcome (curse): Everyone Loves Hookbolts

### PR DESCRIPTION
**Pull request by inks007**
Changes to be committed:
new file:   files/entities/misc/effect_everyone_loves_hookbolts.xml
new file:   files/scripts/effect_everyone_loves_hookbolts.lua
new file:   files/ui_gfx/status_indicators/everyone_loves_hookbolts.png
new file:   files/ui_gfx/status_indicators/everyone_loves_hookbolts_ui.png
new file:   twitch_fragments/outcomes/everyone_loves_hookbolts.lua

### CODE REVIEW

**Comment by inks007** [comment]
I used effect_derandomized_projectiles.lua to apply hookbolts to enemy projectiles.
Copied the spells2worms methods of converting player projectiles to hookbolts.

Comments/suggestions/improvements please.

**Comment by Miczu** [comment]
I didn't see PR notifications... feel free to DM me on discord if you ever create a pr, so I react sooner. I'll review this when I get some spare time today.

**Comment by Miczu** [comment]
I updated your manifest.json so I can point to your branch for testing. I usually use https://www.strerr.com/en/sha256_file.html to calculate sha256 for files that got added/updated.

Looks like the hookbolt behaves weirdly with good number of enemies - they don't maintain horizontal momentum and mostly just jump funny. I suspect ai movement cancels that out or something.

Shots are also hard to dodge. Melee enemies getting fast shots that deal 8 dmg early quite unfair for player. Not sure if this is reversed late game.

Hookbolt can also be used by player to speedrun and I personally want to limit that.

Hookbolt is only available on noita beta branch, so it isn't ready to be added to TI that doesn't restrict that.

Overall, I would prefer to add hookshot to enemy projectile randomize/derandomize over making it its own vote.

**Comment by inks007** [comment]
Ah, the reason why the hookbolt looks a little different on enemies is because I got the hookbolt to adopt the original projectile's speed and vector.

You're right about melee enemies, they should stay with melee attacks only (I thought I did test this). I will need to fix this.

Yes, it's double edged, where it's probably a good effect for the player in the Temple, but bad in the Hiisi Base (the double edged option is the fun bit).

Speedrunning with hookbolt is pretty janky. In the end it's still an option voted in by chat, so its existence isn't necessarily always an advantage to the player.

Beta only, yeah. I was banking on the devs updating main by now.

Since it uses Conga_Lyne's effect_derandomized_projectiles.lua, that'll need to be patched for hookbolt. Probably a condition this line: `ComponentSetValue2( comp, "attack_ranged_enabled", true )`. In this case, though, it no longer affects both enemy and player projectiles...

**Comment by Miczu** [comment]
Probably this is on hold until hookbolts is pushed to main noita branch, so no rush here.

**Comment by Miczu** [comment]
@inks007 they pushed beta to main right? Are we good with moving this forward?

**Comment by inks007** [comment]
Been distracted with other projects. Cooled off quite a bit on this outcome, especially since we've had some other new outcomes. Will withdraw this PR.

**Pull request closed without merging**
