### PR TITLE
Bleeding option

### PR DESCRIPTION
**Pull request by IndoorKat**
Spawns some water on the player every couple of seconds.

### CODE REVIEW

**Comment by IndoorKat** [comment]
Not sure what the rarity should be for this, feel free to adjust.

**Comment by Miczu** [comment]
The outcome has potential, but there is a problem with "Poisoned Water". 
Player will be hit with 50 instances of water in 50 to 150 seconds range. 
With 13-37 that's average 25s between votes and Sweaty lasting on average 100s is 3ish votes to pick poison water and be like Dry spell, but you can't even walk around fire to avoid it.

https://github.com/user-attachments/assets/41653fda-d450-4d7c-ae38-fefc8e6c1253

Only way to salvage this would be to find alternative material to sprinkle on top of player.

**Comment by IndoorKat** [comment]
I was aware that there would be some synergy between the two options, but didn't realise it would be that bad. I'll change the material to oil

**Comment by Miczu** [comment]
What do you think about https://noita.wiki.gg/wiki/Slush instead of oil? Maybe it's closer to sweat than oil as a theme and we can rebrand it to "cold sweats" or something.

**Comment by Miczu** [comment]
Forgot to mention the material image was so big, it dig holes in walls I hug, so maybe could work on that too 👍

**Comment by IndoorKat** [comment]
Slush could work, though it would be pretty annoying to the player as it slows them too (maybe thats a good thing?). Blood and excrement (removes stains) could also work as they can also be seen as bodily fluids (I guess milk works too in that regard).

In regards to the hole digging problem, I've solved it by reducing the number of material pixels which has also nerfed the option a bit as it doesn't stain the player as much (still consistent enough to interrupt invis/ambrosia though). 

What do you think about the material? I think milk could be funny, but may be a bit inappropriate in this context.

**Comment by IndoorKat** [comment]
Excrement wouldn't work actually, because it doesn't apply a stain itself, so it's between blood, slush, and milk.

**Comment by Miczu** [comment]
Maybe we can balance it around the slush slowing effect and reduce duration? I like slush as it should apply wet status that matches the theme. Having an option to physically slow player has it's use too.

**Comment by IndoorKat** [comment]
Slush is a bit weird, it kinda just floats in the air for a bit. 
noita-20240727-184638-1249305330-00008889

**Comment by IndoorKat** [comment]
It's too visually unappealing imo, I think the best option is to do blood and call the effect bleeding or something.

**Comment by Miczu** [comment]
It was listed under liquids on wiki 😭

**Comment by Miczu** [comment]
If you want to try, there is an option of creating custom materials and you could create "water" that makes you wet, but doesn't have tag of "water" to trigger poison water... or call it sweat

**Comment by Miczu** [comment]
Or what abut "sima" or whiskey and it's like "drinks on chat"

**Comment by IndoorKat** [comment]
Tbh making a material that looks like water but doesn't work with poisoned water will just confuse people. The drinks thing is mechanically fine but like oil doesn't really make sense like blood does (also the less additional effects it has the more of an excuse to make it more common, making it a better ambro/invis counter.). I'll stick with blood if that's fine by you?

**Comment by IndoorKat** [comment]
I'll reopen this pull and put the files here

**Comment by IndoorKat** [comment]
Should be all good now

**Comment by Miczu** [comment]
If we are going with bleeding theme, maybe we should trigger the red "I got hurt" screen effect? Probably hurting player for 1 dmg 50 times is too much, but if every 4th effect was also 1dmg loss, that would only be like 12 dmg total.

I don't see code for handling the effect stacking, I suspect  crazy 1-2 vote range will flood screen with blood at some point?
Would be nice to make it as duration extension instead.

Maybe it's worth reusing "swapper curse" code for having status icon and effect duration management.

```
local name = "Bleeding"
add_icon_effect("mods/twitch-integration/files/effects/status_icons/swapper.png", name, "You feel jealous of others position in life", 45*60, function()
	async(function()
		--GamePrint("Start")
		repeat			
			wait(6 * 60)
		until not is_icon_effect_active(name)
	end)
end)
```
PS. this code reminds me that the wait is in frames, so 50 x random(100,300) - like 83 seconds to 250 seconds duration 😂

**Comment by IndoorKat** [comment]
Ok, the effect icon works and now it always goes for 100 seconds (I'm sure a certain old man would complain it was rigged if it was random). For the damage I've used the take damage code to do 1% of the player health (I've made when it occurs kinda random so it can't be predicted), it also momentarily stuns when it procs like take damage.

**Comment by Miczu** [comment]
I'll test it tomorrow. 
Bit worried about the stun part. If my math is correct, the dmg/stun effect should happen like 10 times, so a lot better than the dedicated stun vote option. I'll give more feedback after proper testing.

**Comment by Miczu** [comment]
I tweaked the code to be a bit more predictable with those random rolls.
Here is the current expected hits:
image
So about 10 stuns on average is a bit high.

So I propose reducing it to only 4 stuns of average, but make it even more unpredictable
image
The stuns must be so infrequent, that player isn't forced to wait it out in a corner, but also there is chance that even after a stun, there can be another stun in second or two for perfect comedic effect 😁

**Comment by IndoorKat** [comment]
Looks good

**Review by Miczu — APPROVED** [review]

**Pull request merged**
